### ISSUE TITLE
Anisotropic Material Tensor

### ISSUE THREAD

**Issue by tjdodwell** [david-kamensky/tIGAr#11]
This looks great.

I wondered if you had implemented an anisotropic material law?

Thanks

**Comment by david-kamensky** [comment]
It's not in the demos, but has been done by various users.  See, e.g., the analysis [here](https://doi.org/10.1002/cnm.3438), which used Kirchhoff--Love shells implemented in tIGAr.  Implementing a constitutive model in UFL is easy if you have a closed-form stress--strain relation.  The main practical challenge with anisotropy is typically choosing a way to represent the local material direction(s) rather than implementing the model itself.  However, this is often also problem-specific and dependent on the format of upstream data used to set up the model.
