### ISSUE TITLE
Creating a periodic domain with igakit

### ISSUE THREAD

**Issue by mrudangm** [david-kamensky/tIGAr#15]
Hi David, 

I'm trying to create a periodic NURBS domain using igakit. Specifically, I'm building a periodic annulus following the example in the petiga/igakit docs, https://petiga-igakit.readthedocs.io/en/latest/TUTORIAL3.html. Unfortunately, this throws up an error while creating an EqualOrderSpline. The code and resulting errors are below:

The code
```
from dolfin import *
import ufl
import numpy as np
from tIGAr.BSplines import *            # splines
from tIGAr.NURBS import *               # NURBS

# geometry imports
from igakit.nurbs import NURBS as NURBS_ik
from igakit.io import PetIGA
from igakit import cad

#########################################
c1 = cad.circle()
c2 = cad.circle(radius=2)
srf = cad.ruled(c1,c2).transpose().elevate(0,1)
to_insert = np.linspace(0,0.25,11)[1:-1]
for i in range(4):
    srf.refine(0,i*0.25+to_insert)
    srf.refine(1,i*0.25+to_insert)
srf.unclamp(1) 
PetIGA().write("annulus.dat",srf)

controlMesh = NURBSControlMesh("annulus.dat") 
splineGenerator = EqualOrderSpline(1,controlMesh) 
splineGenerator.writeExtraction("./extraction/")
```

The error
```
  File "Test_3_1.py", line 68, in <module>
    splineGenerator = EqualOrderSpline(1,controlMesh) 
  File "/usr/local/lib/python3.6/dist-packages/tIGAr/common.py", line 157, in __init__
    self.genericSetup()
  File "/usr/local/lib/python3.6/dist-packages/tIGAr/common.py", line 375, in genericSetup
    = self.getHomogeneousCoordinate(I,i)
  File "/usr/local/lib/python3.6/dist-packages/tIGAr/common.py", line 1860, in getHomogeneousCoordinate
    .getHomogeneousCoordinate(node,direction)
  File "/usr/local/lib/python3.6/dist-packages/tIGAr/NURBS.py", line 74, in getHomogeneousCoordinate
    return self.bnet[node,direction]
IndexError: index 1755 is out of bounds for axis 0 with size 1755
```

Is there any way to limit the getHomogeneousCoordinate function? Do you have any recommendations for other ways to create a periodic domain? Thanks! 

Best Regards,
Mrudang

PS: Thanks for all your efforts with tIGAr, this is a great tool for the community!

**Comment by david-kamensky** [comment]
I think igakit follows different conventions for representing periodicity than tIGAr, so periodic splines from igakit are not directly compatible.  tIGAr does have support for periodic splines, and some people have asked me about this through other channels as well, so I just pushed some examples to `demos/periodicity` that you may find helpful.  In summary, tIGAr treats all splines as periodic, where the first and last knots are identified with each other, but, in the case of an open knot vector, the spline space is discontinuous due to this knot having multiplicity $p+1$, so this formal periodicity has no effect.  Hopefully taking a closer look at the new demos will clarify the details.
